# Generated by Django 4.2.4 on 2023-09-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('availability_start', models.TimeField()),
                ('availability_end', models.TimeField()),
                ('society', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('housesize', models.CharField(max_length=100)),
            ],
        ),
    ]
